[package]
name = "avl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.68"
bindgen = "0.58.1"

[dependencies]
bindgen = "0.58.1"
